name: flutter_custom_selector

description: A flexible multi select and single select package for Flutter. Flutter custom selector dart package with awesome UI. Make your selection unique and fantacy

version: 1.1.0

homepage: https://github.com/hbrhbr/flutter_custom_select
repository: https://github.com/hbrhbr/flutter_custom_select
issue_tracker: https://github.com/hbrhbr/flutter_custom_select
documentation: https://github.com/hbrhbr/flutter_custom_select

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: